# Generated by Django 5.2.8 on 2025-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronaldo', '0002_experience_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent', models.PositiveIntegerField()),
                ('last_week', models.PositiveIntegerField(default=28)),
                ('last_month', models.PositiveIntegerField(default=60)),
            ],
        ),
    ]
