# Generated by Django 5.2.8 on 2025-11-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronaldo', '0003_skill_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year_range', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('discription', models.TextField()),
            ],
        ),
    ]
