# Generated by Django 5.2.8 on 2025-11-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronaldo', '0005_counter_1_project_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_1',
            name='link',
        ),
    ]
