# Generated by Django 5.2.8 on 2025-11-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronaldo', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
    ]
