# Generated by Django 5.2.8 on 2025-11-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronaldo', '0008_remove_contact_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
