# Generated by Django 5.2.8 on 2025-11-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronaldo', '0009_rename_first_name_contact_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='full_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='your_name',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
